### ISSUE TITLE
Unable to perform a USB Redirection

### ISSUE THREAD

**Issue by kurobeats** [flathub/org.gnome.Boxes#27]
While following [these instructions](https://help.gnome.org/users/gnome-boxes/stable/usb-redirection.html.en), there are no USB devices available (over 10 currently connected to host):

![Screenshot from 2019-04-13 13-18-09](https://user-images.githubusercontent.com/4091936/56075062-f37a7800-5dee-11e9-96a5-7e180e387812.png)

**Comment by kurobeats** [comment]
Duplicate of https://github.com/flathub/org.gnome.Boxes/issues/2

**Comment by muelli** [comment]
Why does that not work, though? It currently uses  `--device=all` and thus the USB devices should be accessible.

**Comment by kurobeats** [comment]
great question. I have no idea. I've tried on multiple machines to no avail.

**Comment by felipeborges** [comment]
It currently won't work as it is because we need to escalate privileges for that.

To begin with, *spice-client-glib-usb-acl-helper* needs to talk to *polkit*, but for that, it needs to pass the parent PID of the calling application to `polkit_unix_process_new_for_owner`. The tricky part here is that Flatpak has its own namespace and therefore the PID obtained by `getppid()` won't be useful.

Alternatively, we would have to teach spice-gtk to get the right PID. For that, we'd need to bring *libflatpak* in the bundle so we could use `flatpak_instance_get_pid()`. It is in my TODO list.
