### ISSUE TITLE
Shared Folders

### ISSUE THREAD

**Issue by x80486** [flathub/org.gnome.Boxes#3]
I was reading [this](https://alexandruvisarion.wordpress.com/2017/06/15/gnome-boxes-introducing-shared-folders/), and I wonder if `spice-webdavd` is included in the Flatpak build...would that work?

**Comment by Tids** [comment]
+1 for this if possible. Shared folders/devices are really needed in here.

**Comment by felipeborges** [comment]
Thanks for your interest in Boxes!

spice-webdavd is a daemon which you'd install in the guest (operating system running in the VM).

We need a Flatpak portal to be able to do device redirection and such, so that's probably landing in 3.32 (in 6 months from now, at best).

The good news is that you ca already move files into your VM by dragging-and-dropping them, or using the Send File option in the hamburger menu. See https://feborg.es/files/2018/03/New-Project.webm

**Comment by felipeborges** [comment]
Now all the backend for Folder Sharing support has landed in Flathub. Please update.

Make sure your guest OS has the spice agent and spice-webdavd installed. Enjoy!

**Comment by monreal** [comment]
> Make sure your guest OS has the spice agent and spice-webdavd installed. Enjoy!

On Silverblue 33: rpm-ostree install spice-webdavd
