### ISSUE TITLE
Work being done to rebase to 40?

### ISSUE THREAD

**Issue by nickavem** [flathub/org.gnome.Boxes#64]
Is there work being done/has there been work done to pull in Boxes 40?

**Comment by felipeborges** [comment]
Yes, I am about to push it tomorrow. I was looking at a fix to the situation where QEMU is fed a path (from the document-portal) which is not available in the flatpak sandbox, without having to expose the filesystem for that. So far no luck, but I think filesystem access should be acceptable for now, given that otherwise we can only support images within $HOME.

Boxes 40.rc is our flathub-beta btw, if you need it earlier.

**Comment by nickavem** [comment]
Alright, thanks. I just noticed `update-to-40-beta` was mostly finished and was curious if any help was needed.
